title: "Coroio Project"
description: "coroio"

markdown: GFM

theme: minima

minima:
  skin: classic

exclude:
  - README.md
  - LICENSE
  - Gemfile
  - .gitignore
  - docs

header_pages:
  - _pages/benchmarks.md
  - _pages/source.md

include:
  - _pages

github_username: resetius
linkedin_username: alexey-ozeritskiy
twitter_username: resetius
