title: "Coroio Project"
description: "coroio"

markdown: GFM

theme: minima

minima:
  skin: classic

exclude:
  - README.md
  - LICENSE
  - Gemfile
  - .gitignore
  - docs

github_username: resetius
linkedin_username: alexey-ozeritskiy
twitter_username: resetius
