title: "Coroio Project"
description: "coroio"

markdown: GFM

theme: minima

minima:
  skin: classic

exclude:
  - README.md
  - LICENSE
  - Gemfile
  - .gitignore

header_pages:
  - _pages/benchmarks.md
  - _pages/source.md
  - _pages/docs.md

include:
  - _pages
  - docs

github_username: resetius
linkedin_username: alexey-ozeritskiy
twitter_username: resetius


url: "https://coroio.dev" 
plugins:
  - jekyll-sitemap
